
name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'my_dbt_project'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
target-path: "target"  # Directory for compiled SQL files
clean-targets:         # Directories to be cleaned by the `dbt clean` command
  - "target"
  - "dbt_modules"

models:
  my_dbt_project:
    # Applies to all files under models/example/
    staging:
      +materialized: view
      snowflake_warehouse: my_warehouse
    marts:
      +materialized: table
      snowflake_warehouse: my_warehouse


